Enabling Debug logs for Camel K and Strimzi Operator
bf2fc6cc711aee1a0c2a/cos-fleetshard pull request #534
Opened 2022-11-22 20:51 UTC by shivamG640

Hi @valdar, Please review!
I tried building the new addon locally and these changes reflect on the respective csv.yaml.

2022-11-23 18:53 UTC, rinaldodev approved these changes

2022-11-28 10:58 UTC, valdar requested changes

2022-11-28 10:58 UTC, valdar commented on README.adoc
> +Remove the created config map from the namespace to restore the default behavior.
and restart the pod, I would add.

2022-11-28 10:58 UTC, valdar commented on README.adoc
> +Remove the created config map from the namespace to restore the default behavior.
same

2022-11-28 13:12 UTC, valdar approved these changes

2022-11-28 14:27 UTC, merged