chore: replace auto-assign-reviewer-by-files action with CODEOWNERS
bf2fc6cc711aee1a0c2a/cos-fleetshard pull request #543
Opened 2022-11-29 12:22 UTC by lburgazzoli

2022-12-02 15:06 UTC, rinaldodev approved these changes

2022-12-02 15:06 UTC, rinaldodev requested changes
Invalid owner on line 12:
cos-fleetshard-api/**/*" @rinaldodev @valdar @Naros @rk3rn3r

2022-12-02 15:22 UTC, rk3rn3r commented on .github/CODEOWNERS
> +cos-fleetshard-api/**/*" @rinaldodev @valdar @Naros @rk3rn3r
Invalid `"` char

2022-12-02 15:23 UTC, rk3rn3r commented on .github/CODEOWNERS
> +cos-fleetshard-api/**/*" @rinaldodev @valdar @Naros @rk3rn3r
```suggestion
cos-fleetshard-api/**/* @rinaldodev @valdar @Naros @rk3rn3r
```

2022-12-03 18:50 UTC, lgarciaaco approved these changes

2022-12-04 12:23 UTC, lburgazzoli commented
> GitHub is complaning:
> 
> ```
> Invalid owner on line 12:
> cos-fleetshard-api/**/*" @rinaldodev @valdar @Naros @rk3rn3r
> ```

done

2022-12-05 11:55 UTC, rinaldodev approved these changes

2022-12-05 11:55 UTC, merged